### ISSUE TITLE
Panicking causes another panic in `Pool` drop

### ISSUE THREAD

**Issue by pimeys** [blackbeam/mysql_async#88]
Example code:

``` rust
use mysql_async as my;
use std::error::Error;

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    let pool = my::Pool::from_url("mysql://root:prisma@localhost:3306/")?;
    let conn = pool.get_conn().await?;
    panic!("meow");
    Ok(())
}
```

This will then try to disconnect the `Pool` and its connections while it trying to call `tokio::spawn` while the runtime is not active anymore.

Error:

```
thread 'main' panicked at 'meow', src/main.rs:8:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'must be called from the context of Tokio runtime configured with either `basic_scheduler` or `threaded_scheduler`', /home/pimeys/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/global.rs:50:13
```

This is especially nasty in test context, where we've been only getting `SIGILL` on panics.

**Comment by pimeys** [comment]
Oh, and this happens only when using the basic runtime, not the threaded one

``` toml
tokio = { version = "0.2", features = ["macros", "rt-core"] }
```
